services:
  client: 
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /app
    user: 1000:1000
    volumes:
      - ./:/app
    environment:
      - NODE_URLS=http://node1:8080,http://node2:8080,http://node3:8080
    command: dotnet run --project RaftClient
    ports:
    - 4560:8080

  node1:
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /app
    user: 1000:1000
    volumes:
      - ./:/app
    environment:
      - NODE_URLS=http://node1:8080,http://node2:8080,http://node3:8080
    command: dotnet run --project RaftApi

  node2:
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /app
    user: 1000:1000
    volumes:
      - ./:/app
    environment:
      - NODE_URLS=http://node1:8080,http://node2:8080,http://node3:8080
    command: dotnet run --project RaftApi

  node3:
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /app
    user: 1000:1000
    volumes:
      - ./:/app
    environment:
      - NODE_URLS=http://node1:8080,http://node2:8080,http://node3:8080
    command: dotnet run --project RaftApi
